### PR TITLE
Fixed Firefox scroll on OSX

### PR DESCRIPTION
**Pull request by exdeniz**
Add check for OSX and Firefox. For correct scroll on OSX deltaY need multiplier 40.

### CODE REVIEW

**Comment by cmswalker** [comment]
Hi there, sorry this has taken so long to get back to you. I have been busy with work and starting to integrate horizontal sliders. I'm willing to accept this but I don't understand why it wasn't working. I'm running firefox 48.0 on MacOSX Desktop and it is working fine. Do you have any details?

**Comment by exdeniz** [comment]
Firefox 50.1.0, mouse with classic wheel and OSX 10.12

**Comment by cmswalker** [comment]
ah, i see here. I think the issue is the classic wheel. It registers just one event per tick of the wheel. So the average scroll on that is a much smaller interval than using a touchpad. Hopefully Firefox just minimizes the events in a way chrome/safari do not. I don't have a scroll wheel handy at the moment, would you mind letting me know if all works ok with chrome and safari without the multiplier? Thanks again for sticking with this

**Comment by exdeniz** [comment]
In webkit browser classic mouse work is fine.

**Comment by cmswalker** [comment]
Great thank you!

**Pull request merged**
